<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BreedSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('breeds')->insert(['name' => 'Affenpinscher', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Afghan Hound', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'AireDale', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Airedale Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Akita', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Akita Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Akita Shepherd Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Alaskan Klee Kai', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Alaskan Malamute', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Alaskan Malamute mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Alaskan Nanuk', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'American Bulldog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'American Bulldog Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'American Eskimo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'American Eskimo Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'American Eskipoo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'American Shepherd', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'American Staffordshire Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Anatolian Shepherd', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'American Staffordshire Terrier Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Aussiedoodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Austrailian Shepherd', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Australian Cattle Dog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Australian Cattle Dog Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Australian Kelpie', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Australian Shepherd Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Australian Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Australian Terrier Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bahamian Potcake', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Barbet', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Basenji', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Basenji Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Basset Hound', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bassett Hound Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Beagle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Beagle Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bearded Collie', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Beauceron', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bedlington Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Belgain Malinois Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Belgain Malinois', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Belgain Sheep Dog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Belgain Shepard', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Belgain Tervuren', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Berger Blanc Suisse', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Berger Picard', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bernese Mountain Dog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bernedoodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bernese Mountain Dog Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bichon Poodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bichon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bichon Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bichon Shih Tzu Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Biewer Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Black Mouth Cur', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Black Mouth Cur Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'BloodHound', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Blue Heeler', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Blue Heeler Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Blue Lacey', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Blue Nose Pit', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Blue Tick Hound', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Boerboel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bolonka', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Border Collie', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Border Collie Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Border Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Border Terrier Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bouvier Des Flandres', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Boxer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Boxer Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Boykin Spaniel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bracco Italiano', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Brazilian Mastiff', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Briard', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Brittany Spaniel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Brittany Spaniel Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Brussels Griffon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Brussels Griffon Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bull Dog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bull Dog Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bull Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bulldog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bulldog Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Bullmastiff', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Cabachon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Cairn terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Cane Corso', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Conton De Tulear', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Cardigan Welsh Corgi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Carin Terr Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Catahoula', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Catahoula Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Cattle Dog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Cattle Dog Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Cavapoo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Cavachon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Cavalier King Charles spaniel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Cavalier King Charles Spaniel Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Chesapeake Bay Retriever', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Chihuahua', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Chihuahua Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Chinese Crested', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Chiweenie', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Chow Chow', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Chow Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Clumber Spaniel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'CockaPoo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Cocker Spaniel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Cocker Spaniel Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Collie', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Collie Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Coon Hound Treeing Walker', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Coonhound', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Coonhound Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Corgi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Corgi Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Curr', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Curr Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Dachshund', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Dachshund Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Dalmatian', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Dalmatian Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Dingo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Doberman Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Doberman Pinscher', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Dogo Agentino', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Dogo Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Dogo de Bordeaux', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Doxen', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Doxen Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Drahthaar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Duck Tolling Retriever', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Dutch Shepard', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'English Bulldog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'English Cocker Spaniel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'English Cream Golden Retriever', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'English Lab', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'English Mastiff', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'English Pointer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'English Setter', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'English Setter Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'English Shephard', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'English Springer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'English Staffordshire Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'English Working Spaniel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Eurasier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Field Spaniel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Flat Coated Retreiver', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Fox Hound Lab Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Fox Terrier Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Fox Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'French Bordeaux Mastiff', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'French Bulldog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Frenchton', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'German Lab', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'German Malinois', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'German Pinscher', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'German Shepherd Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'German Shepherd', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'German Short haired pointer mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'German Shorthaired Pointer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'German WireHaired Pointer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Goldador', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Golden beagle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Golden Hound Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Golden Retriever', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Golden Retriever Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Goldendoodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Gordon English Setter', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Grand Basset Griffon Vendeen', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Great Dane', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Great Dane Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Great Pyrenees', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Great Pyrenees Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Greater Swiss Mountain Dog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Greyhound', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Greyhound mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Havanese Shitzu', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Havanese Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Havanese', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Havanese Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Heeler Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Holsteiner', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Hound', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Hound Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Husky', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Husky MIx', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Icelandic Sheep dog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Irish Doodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Irish Setter', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Irish Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Irish Wolf Hound', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Italian Bolognese', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Italian Greyhound', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Italian Mastiff', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Italian Spinone', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Jack Russell Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Jack Russell Terrier Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Japanese Chin', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Jindo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Kangel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Keeshond', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Kerry Blue Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Labrador Retriever', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Labrador Retriever Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Lagatto Romagnolo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Lakeland Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Landseer Newfoundland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Large Munsterlander', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Lhasa Apso', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Lhasa apso mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Long Haired Chihuahua', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Long Haired Dachsund', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Lucas Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Maltese', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Maltese Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Manchester Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Manchester Terrier Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Mastiff', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Mastiff Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Mi-Ki', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Minature Dachshund', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Minature Pinscher', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Minature Pinscher Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Minature Poodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Minature Poodle Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Minature Austrailian Shepherd', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Minature Austilian Shepherd Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Minature Bernedoodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Minature Golden Retriever', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Minature Goldendoodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Minature Labradoodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Minature Sheltie', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Minature Wired-haired Dachshund', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Minature American Shepherd', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Minature Schnauzer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Morkie', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Nova Scotia Duck Tolling Retriever', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Neopolitan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Newfipoo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Newfoundland', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Norfolk Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Norwich Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Nowegian Elk Hound', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Ocherese', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Old English Bulldog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Old English Mastiff', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Old English Sheep Dog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Papillon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Papillon Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Parson Russell', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'PeekaPoo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Pekingese', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Pekingese Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Cardigan Welsh Corgi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Pembroke Welsh Corgi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Pharaoh Hound', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Pit Bull', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Pit Bull Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Plott Hound Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Plott Hound', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Pointer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Pointer Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Polish Lowland Sheepdog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Pomeranian', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Pomeranian Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'PomPoo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Pomsky', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Poodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Poodle Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Portuguese Water Dog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Potcake', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Potcake Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Presa Canario', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Pug', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Pug Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Puggle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Puli', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Pyredoodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Queensland Blue Heeler', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Rat Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Rat Terr Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Red Bone Coon Hound', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Red Bone Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Red Fox Lab', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Red Nose Pit', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Red Poodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Red Retriever', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Rhodesian Ridgeback', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Rhodesian Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Rottweiler', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Rottweiler Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Russian Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Saluki', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Samoyed', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Samoyed Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Sapsaree', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Schipperke', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Schipperke Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Schnauzer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Schnauzer Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Schnoodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Scottish Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Scottish Terrier Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Sealyham Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Shar Pei', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Shar-Pei Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Sheep Dog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Sheepadoodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Hungarian Sheepdog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Sheltie', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Sheltie mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Shepherd', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Shepherd Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Shetland Sheep Dog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Shi-Poo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Shiba Inu', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Shiba Inu Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Shih Tzu', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Shih Tzu Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Siberian Husky', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Siberian Husky Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Silky Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Silky Terrier Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Snoodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Soft Coated Wheaton Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Spaniel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Spaniel Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Spanish Water dog', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Spitz', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Springer Spainel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Springer Spaniel Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Springerdoodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'St. Bernedoodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'St. Bernard', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'St. Bernard Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Staffordshire Bull Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Staffordshire Bull Terrier Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Standard Poodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Standard Schnauzer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Sussex Spaniel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Swedish Vallhund', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Tea Cup Chihuahua', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Teacup Schnauzer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Teacup Yorkie', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Teddy Bear', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Terrier Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Texas Heeler', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Thai Ridgeback', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Tibetan Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Toy Aussie', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Toy Poodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Toy Sheltie', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Treeing Walker Coonhound Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Vizsla', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Weimaraner', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Weimaraner Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Welsh Corgi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Welsh Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'West Highland Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Wheaton Terrier Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Whippet', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Whippet Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'White German Shepherd', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Whoodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Wire Haired Pointing Griffon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Wired Hair Fox Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Wired Haired Vizsla', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Wolf-Hybrid', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Wolfadoodle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Yorkshire Terrier', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('breeds')->insert(['name' => 'Yorkie Mix', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
    }
}
